SYSTEM:
  NUM_WORKERS: 8
TRAIN:
  BACKBONE: conformer
  BENCHMARK: fss
  BSZ: 16
  SIA_BSZ: 64
  CATS_AUGMENTATIONS: true
  DECODER_LR: 0.0005
  DECODER_WEIGHT_DECAY: 0.0
  FOLD: 0
  IMG_SIZE: 480
  LR: 0.0005
  LR_SCHEDULER: constant
  MASK: true
  MILESTONES: null
  NITER: 300
  PFENET_AUGMENTATIONS: false
  WEIGHT_DECAY: 0.0
